frr defaults traditional
hostname router_info
log file /var/log/frr.log
service integrated-vtysh-config
!
interface eth0
 ip address 10.0.3.254/24
!
interface eth1
 ip address 10.0.1.253/24
!
router ospf
 ospf router-id 1.1.1.1
 network 10.0.3.0/24 area 0
 network 10.0.1.0/24 area 0
!
line vty
